I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 13, in script
    call screen player_character_sheet_screen
  File "renpy/common/000statements.rpy", line 519, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 15, in execute
    screen player_character_sheet_screen:
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 15, in execute
    screen player_character_sheet_screen:
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 71, in execute
    hbox:
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 74, in execute
    image "[pie_item.img]"
Exception: In DynamicImage u'[pie_item.img]': NameError("Name 'pie_item' is not defined.",)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 13, in script
    call screen player_character_sheet_screen
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ast.py", line 1828, in execute
    self.call("execute")
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ast.py", line 1816, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/statements.py", line 177, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 519, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/exports.py", line 2664, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 2635, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 3019, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 511, in visit_all
    d.visit_all(callback)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 511, in visit_all
    d.visit_all(callback)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 511, in visit_all
    d.visit_all(callback)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/screen.py", line 420, in visit_all
    callback(self)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/core.py", line 3019, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/screen.py", line 430, in per_interact
    self.update()
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/screen.py", line 611, in update
    self.screen.function(**self.scope)
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 15, in execute
    screen player_character_sheet_screen:
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 15, in execute
    screen player_character_sheet_screen:
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 71, in execute
    hbox:
  File "game/screens/character_sheet_screen/player_character_sheet_screen.rpy", line 74, in execute
    image "[pie_item.img]"
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/sl2/sldisplayables.py", line 425, in sl2add
    d = renpy.easy.displayable(d, scope=scope)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/easy.py", line 87, in displayable
    return renpy.display.image.DynamicImage(d, scope=scope)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/image.py", line 476, in __init__
    self.find_target(scope)
  File "/home/gkiss/Misc/renpy-6.99.14.3-sdk/renpy/display/image.py", line 539, in find_target
    raise Exception("In DynamicImage %r: %r" % (self.name, e))
Exception: In DynamicImage u'[pie_item.img]': NameError("Name 'pie_item' is not defined.",)

Linux-4.13.0-38-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.14.3.3347
abstract 1.0
Tue Apr 24 09:17:28 2018
